os:
  - linux

language: go

env:
    - IPFS_REUSEPORT=false

go:
    - 1.8.x
    - 1.9.x

install: true

before_install:
  - make deps

script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
